services:
  espocrm:
    image: espocrm/espocrm:latest
    environment:
      ESPOCRM_DATABASE_HOST: db
      ESPOCRM_DATABASE_NAME: espocrm
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: strongpassword
      ESPOCRM_SITE_URL: https://crm.navrobotec.com
      TZ: Asia/Kolkata
    volumes:
      - espocrm_data:/var/www/html
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - crm_net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - espocrm
      - backup-dashboard
    networks:
      - crm_net
      - web_gateway
    restart: unless-stopped

  backup-dashboard:
    build: ./backup-dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
      - ./scripts:/scripts
    ports:
      - "3030:3030"
    networks:
      - crm_net
    restart: unless-stopped

  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: strongpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Kolkata
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crm_net
    restart: unless-stopped

volumes:
  espocrm_data:
  db_data:


networks:
  crm_net:
    driver: bridge
  web_gateway:
    external: true
